Insert Into COUNTRY_MASTER Values(1,'+91','India');
Insert Into COUNTRY_MASTER Values(2,'+1','Usa');
Insert Into STATES_MASTER Values(1,1,'Andhra Pradesh');
Insert Into STATES_MASTER Values(2,1,'Karnataka');
Insert Into STATES_MASTER Values(3,1,'Odisha');
Insert Into STATES_MASTER Values(4,2,'New Jersy');
insert into STATES_MASTER values(5,2,'Ohio');
Insert Into CITIES_MASTER Values(1,'Vizag',1);
Insert Into CITIES_MASTER Values(2,'Guntur',1);
Insert Into CITIES_MASTER Values(3,'Banglore',2);
Insert Into CITIES_MASTER Values(4,'Mysore',2);
Insert Into CITIES_MASTER Values(5,'Ganjam',3);
Insert Into CITIES_MASTER Values(6,'Nabarangpur',3);
Insert Into CITIES_MASTER Values(7,'Koraput',3);
Insert Into CITIES_MASTER Values(8,'Rayagada',3);
Insert Into CITIES_MASTER Values(9,'Maywood',4);
Insert Into CITIES_MASTER Values(10,'Westwood',4);
Insert Into CITIES_MASTER Values(11,'Oakwood',5);
Insert Into CITIES_MASTER Values(12,'Cuyahoga County',5);